@url = http://localhost:5000

###
GET {{url}}

###
GET {{url}}/api

###
GET {{url}}/parcels/cd79e522-ceee-45da-8a64-8fc707ca0cb3

###
POST {{url}}/parcels

{
  "address": "Test",
  "size": "large",
}